#!/usr/bin/env python3
"""Render the skills catalog table in README.md from scripts/catalog.yaml.

The generated block is written between these markers in README.md:

    <!-- BEGIN SKILLS TABLE (generated by scripts/generate_readme.py) -->
    <!-- END SKILLS TABLE -->

Usage:
    python scripts/generate_readme.py           # rewrite README.md in place
    python scripts/generate_readme.py --check    # exit 1 if README is out of sync
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "scripts" / "catalog.yaml"
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN SKILLS TABLE (generated by scripts/generate_readme.py) -->"
END = "<!-- END SKILLS TABLE -->"


def render_table() -> str:
    data = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    categories = data["categories"]
    skills = data["skills"]

    by_cat: dict[str, list[dict]] = {}
    for skill in skills:
        by_cat.setdefault(skill["category"], []).append(skill)

    lines: list[str] = [f"_{len(skills)} skills across {len(categories)} categories._", ""]
    for cat in categories:
        items = by_cat.get(cat["id"], [])
        if not items:
            continue
        heading = f"{cat.get('emoji', '')} {cat['title']}".strip()
        lines.append(f"### {heading}")
        lines.append("")
        lines.append("| Skill | What it does |")
        lines.append("| --- | --- |")
        for skill in sorted(items, key=lambda s: s["name"]):
            name = skill["name"]
            lines.append(f"| [`{name}`](skills/{name}/SKILL.md) | {skill['blurb']} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def splice(readme_text: str, table: str) -> str:
    if BEGIN not in readme_text or END not in readme_text:
        raise SystemExit("README.md is missing the BEGIN/END skills-table markers")
    pre = readme_text.split(BEGIN)[0]
    post = readme_text.split(END, 1)[1]
    return f"{pre}{BEGIN}\n\n{table}\n{END}{post}"


def main() -> int:
    check = "--check" in sys.argv
    table = render_table()
    current = README.read_text(encoding="utf-8")
    updated = splice(current, table)
    if check:
        if current != updated:
            print("README.md is out of sync with catalog.yaml - run: python scripts/generate_readme.py")
            return 1
        print("README.md is in sync with catalog.yaml.")
        return 0
    README.write_text(updated, encoding="utf-8", newline="\n")
    print("README.md skills table regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
