#!/usr/bin/env python3
"""Render the generated blocks of README.md from the repo's sources of truth.

Two blocks are generated, so they can never drift from the real repo:

  * the badge row  -- skill count from scripts/catalog.yaml, version from
    .claude-plugin/plugin.json -- between:
        <!-- BEGIN BADGES (generated by scripts/generate_readme.py) -->
        <!-- END BADGES -->
  * the skills catalog table -- from scripts/catalog.yaml -- between:
        <!-- BEGIN SKILLS TABLE (generated by scripts/generate_readme.py) -->
        <!-- END SKILLS TABLE -->

Usage:
    python scripts/generate_readme.py           # rewrite README.md in place
    python scripts/generate_readme.py --check    # exit 1 if README is out of sync
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "scripts" / "catalog.yaml"
PLUGIN = ROOT / ".claude-plugin" / "plugin.json"
README = ROOT / "README.md"

BEGIN = "<!-- BEGIN SKILLS TABLE (generated by scripts/generate_readme.py) -->"
END = "<!-- END SKILLS TABLE -->"
BADGES_BEGIN = "<!-- BEGIN BADGES (generated by scripts/generate_readme.py) -->"
BADGES_END = "<!-- END BADGES -->"

REPO = "Deadlymind/nanolama"


def _catalog() -> dict:
    return yaml.safe_load(CATALOG.read_text(encoding="utf-8"))


def render_badges() -> str:
    count = len(_catalog()["skills"])
    version = json.loads(PLUGIN.read_text(encoding="utf-8"))["version"]
    return "\n".join([
        f"[![validate](https://github.com/{REPO}/actions/workflows/ci.yml/badge.svg)]"
        f"(https://github.com/{REPO}/actions/workflows/ci.yml)",
        "[![License: MIT](https://img.shields.io/badge/License-MIT-green.svg)](LICENSE)",
        f"![Skills: {count}](https://img.shields.io/badge/skills-{count}-blue.svg)",
        f"![Version: {version}](https://img.shields.io/badge/version-{version}-blueviolet.svg)",
        "![Stack: Django 5.2 · Next.js 16]"
        "(https://img.shields.io/badge/stack-Django%205.2%20%C2%B7%20Next.js%2016-informational.svg)",
        "[![PRs welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](CONTRIBUTING.md)",
    ])


def render_table() -> str:
    data = _catalog()
    categories = data["categories"]
    skills = data["skills"]

    by_cat: dict[str, list[dict]] = {}
    for skill in skills:
        by_cat.setdefault(skill["category"], []).append(skill)

    lines: list[str] = [f"_{len(skills)} skills across {len(categories)} categories._", ""]
    for cat in categories:
        items = by_cat.get(cat["id"], [])
        if not items:
            continue
        heading = f"{cat.get('emoji', '')} {cat['title']}".strip()
        lines.append(f"### {heading}")
        lines.append("")
        lines.append("| Skill | What it does |")
        lines.append("| --- | --- |")
        for skill in sorted(items, key=lambda s: s["name"]):
            name = skill["name"]
            lines.append(f"| [`{name}`](skills/{name}/SKILL.md) | {skill['blurb']} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _splice(text: str, begin: str, end: str, body: str) -> str:
    if begin not in text or end not in text:
        raise SystemExit(f"README.md is missing the markers: {begin} / {end}")
    pre = text.split(begin)[0]
    post = text.split(end, 1)[1]
    return f"{pre}{begin}\n\n{body}\n{end}{post}"


def splice(readme_text: str, table: str) -> str:
    """Splice the skills table (kept as a named helper for the test suite)."""
    return _splice(readme_text, BEGIN, END, table)


def splice_badges(readme_text: str, badges: str) -> str:
    return _splice(readme_text, BADGES_BEGIN, BADGES_END, badges)


def apply_all(readme_text: str) -> str:
    return splice_badges(splice(readme_text, render_table()), render_badges())


def main() -> int:
    check = "--check" in sys.argv
    current = README.read_text(encoding="utf-8")
    updated = apply_all(current)
    if check:
        if current != updated:
            print("README.md is out of sync - run: python scripts/generate_readme.py")
            return 1
        print("README.md is in sync with catalog.yaml + plugin.json.")
        return 0
    README.write_text(updated, encoding="utf-8", newline="\n")
    print("README.md badges + skills table regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
